// Auto-generated from docs/credit-card-image-scrape-report.json - DO NOT EDIT MANUALLY.
// Regenerate with: python3 scripts/generate-card-visual-status.py
// Maps each card key to its current visual status from the scrape report.
// The verify-credit-card-visuals.ts verifier cross-checks this against the live report
// and will fail if they diverge.
export const SCRAPE_REPORT_STATUS_MAP: Record<string, string> = {
  "aub_gold_mastercard": "clean-card",
  "bdo_american_express_cashback_credit_card": "clean-card",
  "bdo_american_express_explorer_credit_card": "clean-card",
  "bdo_american_express_platinum_credit_card": "clean-card",
  "bdo_diamond_unionpay": "clean-card",
  "bdo_diners_club_international": "clean-card",
  "bdo_diners_club_premiere": "clean-card",
  "bdo_gold_mastercard": "clean-card",
  "bdo_gold_unionpay": "clean-card",
  "bdo_installment_card": "clean-card",
  "bdo_jcb_gold": "clean-card",
  "bdo_jcb_lucky_cat": "clean-card",
  "bdo_jcb_platinum": "clean-card",
  "bdo_platinum_mastercard": "clean-card",
  "bdo_secured_credit_card": "clean-card",
  "bdo_standard_mastercard": "clean-card",
  "bdo_visa_classic": "clean-card",
  "bdo_visa_gold": "clean-card",
  "bdo_visa_platinum": "clean-card",
  "bdo_visa_signature": "clean-card",
  "bdo_world_elite_mastercard": "clean-card",
  "bdo_blue_from_american_express": "clean-card",
  "bpi_amore_cashback_card": "clean-card",
  "bpi_amore_platinum_cashback_card": "clean-card",
  "bpi_edge_card": "clean-card",
  "bpi_gold_rewards_card": "clean-card",
  "bpi_platinum_rewards_mastercard": "clean-card",
  "bpi_signature_card": "clean-card",
  "petron_bpi_card": "clean-card",
  "chinabank_athome_visa_platinum": "clean-card",
  "chinabank_cash_rewards_mastercard": "clean-card",
  "chinabank_destinations_platinum_mastercard": "clean-card",
  "chinabank_destinations_world_dollar_mastercard": "clean-card",
  "chinabank_destinations_world_mastercard": "clean-card",
  "chinabank_freedom_mastercard": "clean-card",
  "eastwest_everyday_titanium_mastercard": "clean-card",
  "eastwest_gold_mastercard": "clean-card",
  "eastwest_platinum_mastercard": "clean-card",
  "eastwest_visa_platinum": "clean-card",
  "equicom_gold_credit_card": "clean-card",
  "metrobank_rewards_plus_visa": "clean-card",
  "metrobank_cashback_visa": "clean-card",
  "rcbc_flex_visa": "clean-card",
  "security_bank_wave_mastercard": "clean-card",
  "hsbc_live_plus_credit_card": "clean-card",
};
